Resources:
  URL099BBF2A:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkStack/URL/Resource
  linkshortenerServiceRoleC12DE2F4:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkStack/linkshortener/ServiceRole/Resource
  linkshortenerServiceRoleDefaultPolicyF83F394C:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: dynamodb:PutItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - URL099BBF2A
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: linkshortenerServiceRoleDefaultPolicyF83F394C
      Roles:
        - Ref: linkshortenerServiceRoleC12DE2F4
    Metadata:
      aws:cdk:path: CdkStack/linkshortener/ServiceRole/DefaultPolicy/Resource
  linkshortener63B477EA:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters707d1d9a2dfdf5e7f72ae31824ece75b48bfef6b7455cabc497f7e285430ec25S3Bucket5163183F
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters707d1d9a2dfdf5e7f72ae31824ece75b48bfef6b7455cabc497f7e285430ec25S3VersionKey061A3F8B
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters707d1d9a2dfdf5e7f72ae31824ece75b48bfef6b7455cabc497f7e285430ec25S3VersionKey061A3F8B
      Handler: index.linkshortener
      Role:
        Fn::GetAtt:
          - linkshortenerServiceRoleC12DE2F4
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          DynamoTable:
            Ref: URL099BBF2A
    DependsOn:
      - linkshortenerServiceRoleDefaultPolicyF83F394C
      - linkshortenerServiceRoleC12DE2F4
    Metadata:
      aws:cdk:path: CdkStack/linkshortener/Resource
      aws:asset:path: /Users/sachingill/aws/cdk/resources/functions/linkshortener
      aws:asset:property: Code
  urlextractorServiceRole897D4A13:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkStack/urlextractor/ServiceRole/Resource
  urlextractorServiceRoleDefaultPolicy54747FB7:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: dynamodb:GetItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - URL099BBF2A
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: urlextractorServiceRoleDefaultPolicy54747FB7
      Roles:
        - Ref: urlextractorServiceRole897D4A13
    Metadata:
      aws:cdk:path: CdkStack/urlextractor/ServiceRole/DefaultPolicy/Resource
  urlextractorF214A0EE:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters47bb2e11f57ae61e3d7bebd7d56f6200ae720413e71e782ff40b655e6ee289d4S3BucketEC5C439D
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters47bb2e11f57ae61e3d7bebd7d56f6200ae720413e71e782ff40b655e6ee289d4S3VersionKeyBFD972A4
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters47bb2e11f57ae61e3d7bebd7d56f6200ae720413e71e782ff40b655e6ee289d4S3VersionKeyBFD972A4
      Handler: index.urlextractor
      Role:
        Fn::GetAtt:
          - urlextractorServiceRole897D4A13
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          DynamoTable:
            Ref: URL099BBF2A
    DependsOn:
      - urlextractorServiceRoleDefaultPolicy54747FB7
      - urlextractorServiceRole897D4A13
    Metadata:
      aws:cdk:path: CdkStack/urlextractor/Resource
      aws:asset:path: /Users/sachingill/aws/cdk/resources/functions/urlextractor
      aws:asset:property: Code
  apiC8550315:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: api
    Metadata:
      aws:cdk:path: CdkStack/api/Resource
  apiCloudWatchRoleAC81D93E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CdkStack/api/CloudWatchRole/Resource
  apiAccount57E28B43:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - apiCloudWatchRoleAC81D93E
          - Arn
    DependsOn:
      - apiC8550315
    Metadata:
      aws:cdk:path: CdkStack/api/Account
  apiDeployment149F1294346804276e98843340842448f343b064:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: apiC8550315
      Description: Automatically created by the RestApi construct
    DependsOn:
      - apiGETECF0BD67
      - apiPOST36368FF5
    Metadata:
      aws:cdk:path: CdkStack/api/Deployment/Resource
  apiDeploymentStagedev96712F43:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: apiC8550315
      DeploymentId:
        Ref: apiDeployment149F1294346804276e98843340842448f343b064
      StageName: dev
    Metadata:
      aws:cdk:path: CdkStack/api/DeploymentStage.dev/Resource
  apiPOSTApiPermissionCdkStackapi621B3AACPOST00B60F94:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - linkshortener63B477EA
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /
            - Ref: apiDeploymentStagedev96712F43
            - /POST/
    Metadata:
      aws:cdk:path: CdkStack/api/Default/POST/ApiPermission.CdkStackapi621B3AAC.POST..
  apiPOSTApiPermissionTestCdkStackapi621B3AACPOST45D6F71D:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - linkshortener63B477EA
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /test-invoke-stage/POST/
    Metadata:
      aws:cdk:path: CdkStack/api/Default/POST/ApiPermission.Test.CdkStackapi621B3AAC.POST..
  apiPOST36368FF5:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - linkshortener63B477EA
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkStack/api/Default/POST/Resource
  apiGETApiPermissionCdkStackapi621B3AACGET834674C2:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - urlextractorF214A0EE
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /
            - Ref: apiDeploymentStagedev96712F43
            - /GET/
    Metadata:
      aws:cdk:path: CdkStack/api/Default/GET/ApiPermission.CdkStackapi621B3AAC.GET..
  apiGETApiPermissionTestCdkStackapi621B3AACGETDA5EF85F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - urlextractorF214A0EE
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: CdkStack/api/Default/GET/ApiPermission.Test.CdkStackapi621B3AAC.GET..
  apiGETECF0BD67:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - urlextractorF214A0EE
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkStack/api/Default/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.44.0,@aws-cdk/assets=1.44.0,@aws-cdk/aws-apigateway=1.44.0,@aws-cdk/aws-applicationautoscaling=1.44.0,@aws-cdk/aws-autoscaling-common=1.44.0,@aws-cdk/aws-cloudwatch=1.44.0,@aws-cdk/aws-dynamodb=1.44.0,@aws-cdk/aws-ec2=1.44.0,@aws-cdk/aws-events=1.44.0,@aws-cdk/aws-iam=1.44.0,@aws-cdk/aws-kms=1.44.0,@aws-cdk/aws-lambda=1.44.0,@aws-cdk/aws-logs=1.44.0,@aws-cdk/aws-s3=1.44.0,@aws-cdk/aws-s3-assets=1.44.0,@aws-cdk/aws-sqs=1.44.0,@aws-cdk/aws-ssm=1.44.0,@aws-cdk/cdk-assets-schema=1.44.0,@aws-cdk/cloud-assembly-schema=1.44.0,@aws-cdk/core=1.44.0,@aws-cdk/custom-resources=1.44.0,@aws-cdk/cx-api=1.44.0,@aws-cdk/region-info=1.44.0,jsii-runtime=node.js/v10.16.3
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters707d1d9a2dfdf5e7f72ae31824ece75b48bfef6b7455cabc497f7e285430ec25S3Bucket5163183F:
    Type: String
    Description: S3 bucket for asset "707d1d9a2dfdf5e7f72ae31824ece75b48bfef6b7455cabc497f7e285430ec25"
  AssetParameters707d1d9a2dfdf5e7f72ae31824ece75b48bfef6b7455cabc497f7e285430ec25S3VersionKey061A3F8B:
    Type: String
    Description: S3 key for asset version "707d1d9a2dfdf5e7f72ae31824ece75b48bfef6b7455cabc497f7e285430ec25"
  AssetParameters707d1d9a2dfdf5e7f72ae31824ece75b48bfef6b7455cabc497f7e285430ec25ArtifactHashAEC661A9:
    Type: String
    Description: Artifact hash for asset "707d1d9a2dfdf5e7f72ae31824ece75b48bfef6b7455cabc497f7e285430ec25"
  AssetParameters47bb2e11f57ae61e3d7bebd7d56f6200ae720413e71e782ff40b655e6ee289d4S3BucketEC5C439D:
    Type: String
    Description: S3 bucket for asset "47bb2e11f57ae61e3d7bebd7d56f6200ae720413e71e782ff40b655e6ee289d4"
  AssetParameters47bb2e11f57ae61e3d7bebd7d56f6200ae720413e71e782ff40b655e6ee289d4S3VersionKeyBFD972A4:
    Type: String
    Description: S3 key for asset version "47bb2e11f57ae61e3d7bebd7d56f6200ae720413e71e782ff40b655e6ee289d4"
  AssetParameters47bb2e11f57ae61e3d7bebd7d56f6200ae720413e71e782ff40b655e6ee289d4ArtifactHash99A9AB0A:
    Type: String
    Description: Artifact hash for asset "47bb2e11f57ae61e3d7bebd7d56f6200ae720413e71e782ff40b655e6ee289d4"
Outputs:
  apiEndpoint9349E63C:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: apiC8550315
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: apiDeploymentStagedev96712F43
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

